FROM node:8.15.1 as base

WORKDIR /app

COPY ./package*.json ./

RUN npm install

FROM alpine:3.17.2

WORKDIR /app

RUN apk add --update nodejs npm curl

COPY --from=base /app/node_modules .

COPY . .

EXPOSE 3000

CMD ["npm","start"]