export const contracts = [
  {
    id: 100,
    name: "MG FARMS",
    start_date: "22/02/22",
    end_date: "22/03/22",
    address: "c/o MG Contractors Panchkula Ind Are PKL Haryana, India",
    area: "171 Acers",
    crop: "Foodgrains",
    amount: "₹ 40,000",
  },
  {
    id: 100,
    name: "MG FARMS",
    start_date: "22/02/22",
    end_date: "22/03/22",
    address: "c/o MG Contractors Panchkula Ind Are PKL Haryana, India",
    area: "171 Acers",
    crop: "Foodgrains",
    amount: "₹ 40,000",
  },
  {
    id: 100,
    name: "MG FARMS",
    start_date: "22/02/22",
    end_date: "22/03/22",
    address: "c/o MG Contractors Panchkula Ind Are PKL Haryana, India",
    area: "171 Acers",
    crop: "Foodgrains",
    amount: "₹ 40,000",
  },
  {
    id: 100,
    name: "MG FARMS",
    start_date: "22/02/22",
    end_date: "22/03/22",
    address: "c/o MG Contractors Panchkula Ind Are PKL Haryana, India",
    area: "171 Acers",
    crop: "Foodgrains",
    amount: "₹ 40,000",
  },
];
